# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

FROM nginx:latest
LABEL org.opencontainers.image.source https://github.com/trustbloc/wallet-sdk

COPY demo/app/build/web /usr/share/nginx/html
